export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';
export const REQUEST = 'REQUEST';

export const GET_KEYWORDS = 'GET_KEYWORDS';
export const GET_COMPONENT_NODES = 'Get_COMPONENT_NODES';
export const CHANGE_CONTEXT ='CHANGE_CONTEXT'; 
export const SET_COMPONENT_NODES = 'SET_COMPONENT_NODES';
export const CHANGE_SELECTED_NODE = "CHANGE_SELECTED_NODE";
export const ADD_COMPONENT_NODE = "ADD_COMPONENT_NODE";